markdown: rdiscount
pygments: true
plugins: ./_plugins
paginate: 8

safe: false

#站点基础配置
title: Chansh
subTitle: Keep on writing.
description: 使用Jekyll搭建的个人博客，使用了zhanxin.lin开发和设计的Violet 2模板
url: http://chansh.tk
feed: /atom.xml

#菜单配置
nav:
  - text: 首页
    url: /index.html
  - text: 文章归档
    url: /archives.html
  - text: 分类目录
    url: /categories.html
  - text: 关于我
    url: /contact.html
  - text: 友情链接
    url: /links.html

#Links
customLinks:
  - item:
    - text: Oilbeater
      url: http://oilbeater.com
    - text: CoolChar
      url: http://coolchar.com
    message: Friends

#theme config
themes: /themes/violet

#配置你喜欢的顶部背景图片
headimg:
  - item: /themes/violet/images/hdbg01.jpg
  - item: /themes/violet/images/hdbg02.jpg
  - item: /themes/violet/images/hdbg03.jpg
  - item: /themes/violet/images/hdbg04.jpg

#关注我
follow:
  - class: fa-google-plus
    url:
  - class: fa-facebook
    url: 
  - class: fa-github
    url: 
  - class: fa-weibo
    url: 
  - class: fa-renren
    url: 
  - class: fa-pinterest
    url: 
  - class: fa-twitter
    url: 
  - class: fa-rss
    url: 

#作者信息
author:
  link: /contact.html
  img: http://tp2.sinaimg.cn/1832671293/180/40020872447/1

#评论信息
disqus:
  config: false 
  id: chansh

duoshuo:
  config: true
  id: chansh
